### ISSUE TITLE
Version 1.16 breaks python 2.6

### ISSUE THREAD

**Issue by benningm** [Kentzo/git-archive-all#39]
Used python(RHEL6) is:

```
# python --version
Python 2.6.6
```

The latest changes to the format() patterns break old python versions:

```
Traceback (most recent call last):
  File "/usr/local/bin/git-archive-all", line 494, in <module>
    main()
  File "/usr/local/bin/git-archive-all", line 488, in main
    archiver.create(output_file_path, options.dry_run)
  File "/usr/local/bin/git-archive-all", line 118, in create
    self.LOG.debug("Output format is not explicitly set, determined format is {}.".format(output_format))
ValueError: zero length field name in format
```

Reverting {} back to {0} fixes the problem.

**Comment by Kentzo** [comment]
@benningm Ah I new it would break something. This project desperately needs tests…

**Comment by Kentzo** [comment]
@benningm Please check current master

**Comment by benningm** [comment]
thx
